# Generated by Django 4.2.6 on 2023-10-25 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('one_bed', models.IntegerField()),
                ('name', models.CharField(max_length=55)),
                ('two_bed', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('is_prepayment', models.BooleanField(default=False)),
                ('min_prepayment', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=225)),
                ('banned', models.BooleanField(default=False)),
                ('ban_reason', models.CharField(blank=True, null=True)),
                ('role', models.ManyToManyField(to='crmbackend.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crmbackend.users')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('pass_seria', models.IntegerField(max_length=4)),
                ('pass_num', models.IntegerField(max_length=6)),
                ('email', models.CharField(max_length=85)),
                ('phone_number', models.IntegerField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='House_Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField()),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmbackend.houses')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.CharField(blank=True, null=True)),
                ('total_coast', models.FloatField()),
                ('prepayment', models.FloatField()),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmbackend.houses')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmbackend.status')),
                ('profile_id', models.ManyToManyField(to='crmbackend.profiles')),
            ],
        ),
    ]
